-- Rat
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (1, 1, 1, 'Good', 'Both of you are committed to your relationship and feel deeply attached to family life. You know each other so well that you might feel a lack of mystery. You are a shrewd couple with constant calculation.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (2, 1, 2, 'Good', 'You''re a happy couple with willingness to share family responsibility. You have complementary characters and will help each other in your work and home lives.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (3, 1, 5, 'Good', 'You are both mature and confident, which enables you to trust and give privacy to each other. You have a bright future ahead, because you are both optimistic and aspiring in looking for joy in marriage life.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (4, 1, 9, 'Good', 'Both of you can understand and tolerate each other. You are able to work together and support each other. Understanding and care is the best solution when divisions come up.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (5, 1, 4, 'Bad', 'Both have good qualities, but you are not a perfect couple, because you each love yourself too much to spare love for the other. You are true to each other, but the monotonous daily life makes you feel bored.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (6, 1, 7, 'Bad', 'You are both aggressive and take the initiative, which can result in a divergence of opinion.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (7, 1, 10, 'Bad', 'Your compatibility is not very strong because you don''t quite understand each other.');

-- Ox
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (8, 2, 1, 'Good', 'You will be a happy couple with willingness to share family responsibility.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (9, 2, 6, 'Good', 'You are an ideal couple. Both share the same aspirations for life and head in the same direction.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (10, 2, 10, 'Good', 'Without a doubt you are a happy and harmonious couple. You are both talented and competent in their careers and fields, with down-to-earth and responsible approaches to life.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (11, 2, 3, 'Bad', 'You are a couple with little in common. It is possible that you get together out of novelty. Though you both make efforts, you might not be able to reach a true and deeper understanding of each other.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (12, 2, 7, 'Bad', 'Your tempos and personalities are quite different, so you find it difficult to coordinate with each other.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (13, 2, 8, 'Bad', 'You are a quarrelsome couple, and your relationship is full of ups and downs. You are not prepared for differences in opinion, which makes you feel disappointed about your relationship.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (14, 2, 9, 'Bad', 'You have common goals, but your opinions differ. You are two independent people with your own opinions, and you don''t trust each other whole-heartedly.');

-- Tiger
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (15, 3, 7, 'Good', 'Both of you are outgoing and sociable, which makes you a lively and suited couple.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (16, 3, 11, 'Good', 'You are a loving couple with genial and charming personalities. You understand and support each other and know how to give each other personal space.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (17, 3, 12, 'Good', 'You are an ideal and devoted couple, always encouraging each other. Both of you are lively and place importance on the other''s well-being. You trust each other, have common pursuits, and feel free and relaxed when together.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (18, 3, 2, 'Bad', 'Both are stubborn. You are a couple with much inconsistency. There is a long way to go before you can find common ground in your relationship.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (19, 3, 6, 'Bad', 'You are not frank with each other. Both of you are observant and want private space for themselves. The relationship cannot go further if you don''t try to open up and discover each other''s positive sides.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (20, 3, 8, 'Bad', 'You are a couple with quite different personalities, which means that it takes much effort for you to understand and tolerate each other.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (21, 3, 9, 'Bad', 'You are not on the same wavelength. Though genial, outgoing and lively, you don''t have common values.');

-- Rabbit
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (22, 4, 8, 'Good', 'Both are gentle. You are good at resolving disputes. Your marriage is predicted to be happy without much conflict.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (23, 4, 11, 'Good', 'The Dog is the best zodiac sign for the Rabbit. Both of you love life, love family, and are good at socializing. You have many things in common. You don''t rely on each other, but care a lot about each other''s feelings. A happy married life is predicted.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (24, 4, 12, 'Good', 'Easily satisfied, the Rabbit and the Pig are usually happy with each other. Both of you are not picky about life and would feel fulfilled in their marriage.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (25, 4, 1, 'Bad', 'The Rabbit is usually not happy with the Rat''s irresponsibility and the Rat complains about Rabbits'' being too concerned with details. Arguments are common in your marriage.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (26, 4, 10, 'Bad', 'You don''t seem to please each other. You are full of complaints. A couple made up of a Rabbit and a Rooster usually don''t have luck in making money.');

-- Dragon
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (27, 5, 1, 'Good', 'You are a financially wise couple who will establish a steady and fairly well-off family.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (28, 5, 9, 'Good', 'You are an ideal couple. Both are romantic while still being sensible. You have good interpersonal skills and are popular amongst your friends. You admire each other and strive for common goals together.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (29, 5, 10, 'Good', 'Both of you are clever, capable, and independent people. You need to make further communication, try to understand each other and seek common ground.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (30, 5, 11, 'Bad', 'You are a couple full of conflicts. Both of you are vain, temperamental and aggressive. Though you have common goals, you don''t have good understanding towards each other. To make the relationship work, both of you need to make extra efforts, and make a change in your personalities to suit each other.');

-- Snake
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (31, 6, 2, 'Good', 'You are a couple deeply attached to and reliant on each other. Both of you are prudent, realistic and diligent.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (32, 6, 10, 'Good', 'You are a complementary couple who feel content with each other. Your relationship has positive effects on both of you and makes your life better. You understand each other quite well, and are willing to provide full support for one another.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (33, 6, 3, 'Bad', 'You are not a well-suited couple. You are both impulsive, suspicious and harsh, which makes it hard for you to get along well. It is not easy for you to build deep trust and understanding towards each other.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (34, 6, 7, 'Bad', 'You are not very deeply attached to each other. Your values for life do not seem to agree.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (35, 6, 12, 'Bad', 'You have quite different personalities, which makes you an unsuited couple.');

-- Horse
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (36, 7, 3, 'Good', 'You are a couple with a lot in common and strive for the same goals. Both of you are energetic, which brings much happiness to the relationship. In terms of family duties, you understand each other and have smooth cooperation.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (37, 7, 8, 'Good', 'You are a complementary and happy couple. You have different talents and personalities, but you share common goals and values. Your relationship brings out the best in you both and offsets your shortcomings.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (38, 7, 11, 'Good', 'You will have a lasting relationship and grow old together. Both of you are outgoing, energetic, and coordinated, which will help you build a family full of joy.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (39, 7, 1, 'Bad', 'You are not deeply attached to each other. Both of you are very talented people with your own opinions.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (40, 7, 2, 'Bad', 'You have very different personalities, and lack common interests and habits. Your relationship usually lacks laughter and romance.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (41, 7, 6, 'Bad', 'You are both talented and efficient people. It is not easy for you to develop a sense of reliance towards each other. You should be willing to compromise and make more efforts to make the relationship better.');

-- Goat
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (42, 8, 4, 'Good', 'You are an ideal couple. Both of you are attentive and caring, which makes your relationship smooth and joyous.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (43, 8, 7, 'Good', 'You are closely attached to each other and supportive of one another, which makes your relationship smooth and steady.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (44, 8, 8, 'Good', 'You are closely attached to each other and reliant on one another. You input much emotion and effort into your relationship, and deeply love each other. The male goat works hard to feed the family, and the female goat is very supportive and encouraging.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (45, 8, 12, 'Good', 'You are a sweet couple. Both of you are deeply attached to family life and are willing to compromise. There are rarely any conflicts in your relationship.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (46, 8, 2, 'Bad', 'You both need to make joint efforts and changes to make your relationship go smoothly.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (47, 8, 3, 'Bad', 'You are not a well-suited couple. The goat is gentle and romantic, while the tiger is strong, full of enthusiasm and unrestraint. Neither of you can act your part well as husband or wife.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (48, 8, 11, 'Bad', 'You are not a well-suited couple. Both of you are willing to make efforts, but the results often turn out contrary to your expectations.');

-- Monkey
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (49, 9, 1, 'Good', 'You are a couple capable of building a well-off family. You have common goals and are supportive of one another.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (50, 9, 5, 'Good', 'You can bond with each other in a perfect way. Both of you are ambitious and positive, and have objective thoughts. Marriage would create the same angles for you both, and your family would display good orderliness, that you produce by learning from and helping each other. You both know the importance of cherishing and understanding one another. Meanwhile, you love to excavate the other''s advantages, and inspire vitality, making your life endlessly colorful.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (51, 9, 11, 'Good', 'You treat each other in an appreciative way and know each other''s needs. Both of you will become more mature through marriage.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (52, 9, 2, 'Bad', 'Both being stubborn, self-centered, and unwilling to compromise, you lack mutual understanding and don''t get along very well.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (53, 9, 3, 'Bad', 'You are both self-centered and calculating, unwilling to compromise. You pay much attention to your own interests and success, and try to avoid family responsibilities. If you are willing to open up, make frank communication and compromise, your relationship will get much better.');

-- Rooster
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (54, 10, 2, 'Good', 'You are a couple who wins admiration from everyone, and will live to old age in great bliss. Both of you are responsible towards your family and devote the best of yourselves to it. Your marriage will be an ideal example to others.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (55, 10, 5, 'Good', 'Your marriage will get much applause from others and you will have endless bliss. Due to your personalities and abilities, you match each other perfectly. You can understand and help each other well, and are a good example of an affectionate couple.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (56, 10, 6, 'Good', 'You are a complementary couple who feel content with each other. Your relationship has positive effects on both of you and makes your life better. You understand each other quite well, and are willing to provide full support for one another.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (57, 10, 1, 'Bad', 'You have a lot of things to argue about. Both of you have clear-cut personalities, and don''t compromise for each other.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (58, 10, 4, 'Bad', 'You are a couple that has difficulties in enjoying love. Your personalities can''t be together in a harmonious way, and marriage doesn''t inspire your potential, which leads to family disputes.');

-- Dog
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (59, 11, 3, 'Good', 'You were born a couple. You are both idealists who are optimistic, kindhearted, and generous. Your relationship is quite successful.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (60, 11, 4, 'Good', 'You are both zealous for life and good at interpersonal skills. You are frank to each other, and your relationship is happy and harmonious. In your relationship you can show your true colors, but that does not put you into conflicts.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (61, 11, 7, 'Good', 'Though you lack comprehensive and deep communication and understanding towards each other, you both are willing to commit to improvement and make efforts. You can establish a happy lively family through mutual effort.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (62, 11, 9, 'Good', 'Your marriage will last long and help you achieve your common goals, as long as you are generous and tolerant towards each other.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (63, 11, 5, 'Bad', 'You are not true to each other. You are both vigilant and want to steer the family. If you want the relationship to work out, you need to cherish and show appreciation to each other.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (64, 11, 8, 'Bad', 'You are not a well-suited couple. Both of you are used to single life and need to learn how to go on as a couple. You have very different personalities and often face conflicts.');

-- Pig
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (65, 12, 3, 'Good', 'You are a couple strongly attracted to each other and know how to please one another. Both of you are motivated and dynamic, and your shared merits and goals often offset possible conflicts.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (66, 12, 4, 'Good', 'You are a committed couple and are satisfied with each other. You both admire each other''s merits and are willing to make efforts for the family.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (67, 12, 8, 'Good', 'You are an adorable and inseparable couple, who are deeply in love with each other, and are willing to compromise.');
INSERT INTO compatibility (id, zodiac1_id, zodiac2_id, compatibility_type, description) VALUES (68, 12, 6, 'Bad', 'You both should cherish and learn to discover the merits in each other, otherwise your marriage might not end up in a satisfactory state.');
