apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: astropa-database
  namespace: astropa
  labels:
    app: astropa
    component: database
spec:
  serviceName: astropa-database
  replicas: 1
  selector:
    matchLabels:
      app: astropa
      component: database
  template:
    metadata:
      labels:
        app: astropa
        component: database
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: mariadb
        image: mariadb:10.11
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: astropa-secrets
              key: database-password
        - name: MYSQL_DATABASE
          value: astropa
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: astropa-secrets
              key: database-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: astropa-secrets
              key: database-password
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: config
          mountPath: /etc/mysql/conf.d
          readOnly: true
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 3
      volumes:
      - name: config
        configMap:
          name: astropa-database-config
      - name: init-scripts
        configMap:
          name: astropa-database-init
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: astropa-database
  namespace: astropa
  labels:
    app: astropa
    component: database
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  clusterIP: None
  selector:
    app: astropa
    component: database

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: astropa-database-config
  namespace: astropa
  labels:
    app: astropa
    component: database
data:
  my.cnf: |
    [mysqld]
    # Performance settings
    innodb_buffer_pool_size = 128M
    innodb_log_file_size = 32M
    innodb_log_buffer_size = 8M
    innodb_flush_log_at_trx_commit = 2
    innodb_file_per_table = 1
    
    # Connection settings
    max_connections = 100
    max_connect_errors = 1000000
    
    # Security settings
    skip-name-resolve
    
    # Character set
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    
    # Binary logging
    log-bin = mysql-bin
    binlog_format = ROW
    expire_logs_days = 7

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: astropa-database-init
  namespace: astropa
  labels:
    app: astropa
    component: database
data:
  001-init.sql: |
    -- Create zodiac data tables if they don't exist
    CREATE TABLE IF NOT EXISTS zodiacs (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(50) NOT NULL,
        element VARCHAR(20) NOT NULL,
        start_year INT NOT NULL,
        INDEX idx_start_year (start_year)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
    
    -- Insert initial zodiac data
    INSERT IGNORE INTO zodiacs (name, element, start_year) VALUES
    ('Rat', 'Metal', 1900),
    ('Ox', 'Metal', 1901),
    ('Tiger', 'Water', 1902),
    ('Rabbit', 'Water', 1903),
    ('Dragon', 'Wood', 1904),
    ('Snake', 'Wood', 1905),
    ('Horse', 'Fire', 1906),
    ('Goat', 'Fire', 1907),
    ('Monkey', 'Earth', 1908),
    ('Rooster', 'Earth', 1909),
    ('Dog', 'Metal', 1910),
    ('Pig', 'Metal', 1911);

---
apiVersion: v1
kind: Service
metadata:
  name: astropa-database-headless
  namespace: astropa
  labels:
    app: astropa
    component: database
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  clusterIP: None
  selector:
    app: astropa
    component: database