apiVersion: v1
kind: Namespace
metadata:
  name: astropa
  labels:
    app: astropa
    environment: base
---
apiVersion: v1
kind: LimitRange
metadata:
  name: astropa-limits
  namespace: astropa
spec:
  limits:
  - default:
      memory: "512Mi"
      cpu: "500m"
    defaultRequest:
      memory: "256Mi"
      cpu: "250m"
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: astropa-quota
  namespace: astropa
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "4"